const ONE_DAY = 24 * 60 * 60 * 1000;
const ONE_MINUTE = 60 * 1000;

export const SERVER_URL = process.env.REACT_APP_SERVER_URL;
export const COUNTRIES_CACHE_EXPIRY =
  process.env.REACT_APP_COUNTRIES_CACHE_EXPIRY || ONE_DAY;
export const EXCHANGE_RATES_CACHE_EXPIRY =
  process.env.REACT_APP_EXCHANGE_RATES_CACHE_EXPIRY || ONE_MINUTE;
